version: "3"
services:
    database:
        image: postgres
        container_name: database
        hostname: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
            - $HOME/docker/volumes/db_backup:/var/db_backup
        restart: unless-stopped
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5
